#!/usr/bin/env bash

if [ -z "$XDG_CONFIG_HOME" ]; then
	echo "No xdg config homie"
	echo "using ~/.config"
	XDG_CONFIG_HOME=$HOME/.config
fi

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm -a=x -type f)

while [[ $# > 0 ]]; do
	if [[ "$1" == "--dry" ]]; then
		dry="1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute: $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "------------ dev-env ------------"

copy_dir() {
	from=$1
	to=$2

	pushd $from
	dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
	for dir in $dirs; do
		execute rm -rf $to/$dir
		execute cp -r $dir $to/$dir
	done
	popd
}

copy_file() {
	from=$1
	to=$2
	name=$(basename $from)

	execute rm $to/$name
	execute cp $from $to/$name
}

copy_dir .config $XDG_CONFIG_HOME
copy_dir .local $HOME/.local
copy_file env/.bash_profile $HOME
copy_file env/.tmux-sessionizer $HOME
